### ISSUE TITLE
`fetch_by_xxx` is trying to connect to a different url?

### ISSUE THREAD

**Issue by pallymore** [Shopify/identity_cache#216]
Hello, 

I'm using `identity_cache` along with `redis-rails` in my app. It has been working fine for the past year until recently we keep running into issues with some old code. (we recently upgraded to rails 4.2.3 - it could be related but i haven't verified that)

so basically i have a model that looks like this

```ruby
class ItemWording < ActiveRecord::Base
  include IdentityCache
  cache_index :item_id, :locale
end
```

when I try to use `ItemWording.fetch_by_item_id_and_locale` it throws this error:
```
Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
	from /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:331:in `rescue in establish_connection'
	from /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:317:in `establish_connection'
	from /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:94:in `block in connect'
	from /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:279:in `with_reconnect'
	from /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:93:in `connect'
	from /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:350:in `ensure_connected'
	from /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:207:in `block in process'
	from /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:292:in `logging'
	from /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:206:in `process'
	from /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:112:in `call'
	from /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis.rb:807:in `block in mget'
	from /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
	from /app/vendor/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
	from /app/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis.rb:806:in `mget'
	from /app/vendor/bundle/ruby/2.2.0/gems/redis-store-1.1.6/lib/redis/store/marshalling.rb:22:in `mget'
... 8 levels...
	from /app/vendor/bundle/ruby/2.2.0/gems/identity_cache-0.2.5/lib/identity_cache.rb:134:in `each_with_object'
	from /app/vendor/bundle/ruby/2.2.0/gems/identity_cache-0.2.5/lib/identity_cache.rb:134:in `fetch_in_batches'
	from /app/vendor/bundle/ruby/2.2.0/gems/identity_cache-0.2.5/lib/identity_cache.rb:115:in `fetch_multi'
	from /app/vendor/bundle/ruby/2.2.0/gems/identity_cache-0.2.5/lib/identity_cache/query_api.rb:59:in `block in fetch_multi'
	from /app/vendor/bundle/ruby/2.2.0/gems/identity_cache-0.2.5/lib/identity_cache/query_api.rb:154:in `require_if_necessary'
	from /app/vendor/bundle/ruby/2.2.0/gems/identity_cache-0.2.5/lib/identity_cache/query_api.rb:54:in `fetch_multi'
	from /app/vendor/bundle/ruby/2.2.0/gems/identity_cache-0.2.5/lib/identity_cache/configuration_dsl.rb:206:in `identity_cache_multiple_value_dynamic_fetcher'
	from /app/vendor/bundle/ruby/2.2.0/gems/identity_cache-0.2.5/lib/identity_cache/configuration_dsl.rb:64:in `fetch_by_question_item_id_and_locale'
	from (irb):4
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from /app/bin/rails:8:in `require'
	from /app/bin/rails:8:in `<main>'irb(main):005:0>
```
this happens in production(deployed to heroku) - web, worker, and console dynos. 
again, this code used to work in the past until recently. We are using RedisCloud and we didn't change any configuration during the upgrade. 
at the same time, other models which are using `Model.fetch(:id)` doesn't seem to be affected, but all the `fetch_by_xxx` calls are broken.

-P

**Comment by arthurnn** [comment]
For some reason, `each_with_object` IDC method, is calling redis.. I would try to debug that.. super wierd, never saw this problem before.

**Comment by camilo** [comment]
Are you sure that by accident you did not use redis as your backend? This is very odd and hard to debug without more info I'll close feel free to reopen if it is still a problem.
