### ISSUE TITLE
calling klass on reflections of yet unloaded classes

### ISSUE THREAD

**Issue by lolownia** [Shopify/identity_cache#219]
I am creating a new issue because I have created a mini-example: a simple padrino app with activerecord and just two models:
https://github.com/lolownia/identity_cache_bug

running rake or padrino ( like `rake ar:migrate` or `padrino start`) will trigger 
```
 ERROR -  IdentityCache::AlreadyIncludedError - IdentityCache::AlreadyIncludedError:
 /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/gems/identity_cache-0.2.5/lib/identity_cache.rb:41:in `included'
/Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/gems/identity_cache-0.2.5/lib/identity_cache.rb:41:in `included': IdentityCache::AlreadyIncludedError (IdentityCache::AlreadyIncludedError)
	from /Users/marcin/Projects/ci_test2/models/bar.rb:4:in `include'
	from /Users/marcin/Projects/ci_test2/models/bar.rb:4:in `<class:Bar>'
	from /Users/marcin/Projects/ci_test2/models/bar.rb:1:in `<top (required)>'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/gems/padrino-core-0.12.5/lib/padrino-core/reloader.rb:95:in `block in safe_load'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/gems/padrino-core-0.12.5/lib/padrino-core/reloader.rb:304:in `with_silence'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/gems/padrino-core-0.12.5/lib/padrino-core/reloader.rb:95:in `safe_load'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/gems/padrino-core-0.12.5/lib/padrino-core/loader.rb:141:in `block in require_dependencies'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/gems/padrino-core-0.12.5/lib/padrino-core/loader.rb:139:in `each'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/gems/padrino-core-0.12.5/lib/padrino-core/loader.rb:139:in `require_dependencies'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/gems/padrino-core-0.12.5/lib/padrino-core/loader.rb:58:in `load!'
	from /Users/marcin/Projects/ci_test2/config/boot.rb:46:in `<top (required)>'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/gems/padrino-core-0.12.5/lib/padrino-core/cli/launcher.rb:25:in `require'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/gems/padrino-core-0.12.5/lib/padrino-core/cli/launcher.rb:25:in `start'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/gems/padrino-core-0.12.5/bin/padrino:9:in `<top (required)>'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/bin/padrino:23:in `load'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/bin/padrino:23:in `<main>'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/bin/ruby_executable_hooks:15:in `eval'
	from /Users/marcin/.rvm/gems/ruby-2.0.0-p643@speakout/bin/ruby_executable_hooks:15:in `<main>'
```
..but this bug is triggered by `build_recursive_association_cache` where `cache_has_many :foos, :embed => true` tries to call `reflect_on_association(association).klass` which is not yet loaded (uninitialized constant)

**Comment by dylanahsmith** [comment]
Closing since this is needed to setup after_commit hooks on the child class to expire the cache on the association when there are changes.  Just use rails auto-loading or require the child model before calling `cache_has_many`
