### ISSUE TITLE
Getting TypeError when calling Model.fetch(id)

### ISSUE THREAD

**Issue by shwetabhgarg** [Shopify/identity_cache#346]
Steps:
- Added gems to Gemfile as given in README
- Bundle install
- Added code to development.rb as given in README
- Added initializer as given in README
- In model called Manufacturer, added "include IdentityCache"

In rails console, running find(1) on the model prints the correct object. However, when fetch(1) is run on the model, it results in an error. Error log:

```
2.4.0 :001 > Catalog::Manufacturer.find 1
  Catalog::Manufacturer Load (0.5ms)  SELECT  `catalog_manufacturers`.* FROM `catalog_manufacturers` WHERE `catalog_manufacturers`.`id` = 1 LIMIT 1
 => #<Catalog::Manufacturer id: 1, name: "man1", manufacturer_entity_name: nil, manufacturer_mapping_id: nil, created_at: "2017-06-25 19:02:42", updated_at: "2017-06-25 19:02:42"> 

2.4.0 :002 > Catalog::Manufacturer.fetch 1
Cache cas: IDC:7:blob:Catalog::Manufacturer:4888547596528694102:1
  Catalog::Manufacturer Load (0.5ms)  SELECT  `catalog_manufacturers`.* FROM `catalog_manufacturers` WHERE `catalog_manufacturers`.`id` = 1 LIMIT 1
Cache write: IDC:7:blob:Catalog::Manufacturer:4888547596528694102:1 ({:unless_exist=>true})
TypeError: no implicit conversion of ActiveSupport::Cache::Entry into String
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/memcached-1.8.0/lib/memcached/memcached.rb:337:in `memcached_add'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/memcached-1.8.0/lib/memcached/memcached.rb:337:in `add'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/memcached-1.8.0/lib/memcached/rails.rb:154:in `add'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/memcached_store-1.1.0/lib/active_support/cache/memcached_store.rb:177:in `block in write_entry'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/memcached_store-1.1.0/lib/active_support/cache/memcached_store.rb:248:in `handle_exceptions'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/memcached_store-1.1.0/lib/active_support/cache/memcached_store.rb:176:in `write_entry'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/activesupport-5.0.2/lib/active_support/cache/strategy/local_cache.rb:118:in `write_entry'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/activesupport-5.0.2/lib/active_support/cache.rb:398:in `block in write'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/activesupport-5.0.2/lib/active_support/cache.rb:562:in `block in instrument'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/activesupport-5.0.2/lib/active_support/notifications.rb:166:in `instrument'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/activesupport-5.0.2/lib/active_support/cache.rb:562:in `instrument'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/activesupport-5.0.2/lib/active_support/cache.rb:396:in `write'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/memcached_store-1.1.0/lib/active_support/cache/memcached_store.rb:45:in `write'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/identity_cache-0.5.1/lib/identity_cache/cache_fetcher.rb:84:in `add'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/identity_cache-0.5.1/lib/identity_cache/cache_fetcher.rb:42:in `fetch'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/identity_cache-0.5.1/lib/identity_cache/memoized_cache_proxy.rb:57:in `fetch'
... 7 levels...
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/shwetabh/workspace/inventory/bin/rails:9:in `<top (required)>'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/shwetabh/.rvm/gems/ruby-2.4.0@inventory-gemset/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
	from /Users/shwetabh/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/shwetabh/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

2.4.0 :003 >

```

As best as I can understand, the error occurs when the database query result is serialized for populating the cache. Any idea what am I missing here?

**Comment by shwetabhgarg** [comment]
Update: Replaced gem `memcached_store` with `redis-rails`. It works like a charm now. We don't have any existing cache servers in our system, so we can go ahead with Redis instead of Memcache.

I'm concluding that the reported issue is in the gem `memcached_store`, not `identity_cache`. Closing this issue.
