### ISSUE TITLE
What is the correct way to configure memcached?

### ISSUE THREAD

**Issue by mani47** [Shopify/identity_cache#450]
Configuration in readme file is really confusing and doesn't work for me:

```ruby
config.identity_cache_store = :memcached_store, Memcached::Rails.new(
      servers: memcached_hosts,
      support_cas: true,
      auto_eject_hosts: false,  # avoids more cache consistency issues
      expires_in: 6.hours.to_i, # in case of network errors when sending a delete
    )
```

Returns this error:

```bash
.rvm/gems/ruby-2.5.7/gems/memcached-1.8.0/lib/memcached/memcached.rb:115:in `block in initialize': :expires_in is not a valid configuration parameter. (ArgumentError)
```

Looking at the source code of memcached, correct parameter is `default_ttl`, using this config:

```ruby
config.identity_cache_store = :memcached_store, Memcached::Rails.new(
      servers: memcached_hosts,
      support_cas: true,
      auto_eject_hosts: false,  # avoids more cache consistency issues
      default_ttl: 6.hours.to_i, # in case of network errors when sending a delete
    )
```

then gives this error: 

```bash
.rvm/gems/ruby-2.5.7/gems/memcached_store-2.1.4/lib/active_support/cache/memcached_store.rb:71:in `initialize': Memcached::Rails is no longer supported, use a Memcached instance instead (RuntimeError)
```

On some other issues #211 and the source code of IdentityCache itself in `test/helpers/cache_connection.rb` I saw that `ActiveSupport::Cache::MemcachedStore.new` is used:

```ruby
config.identity_cache_store = :memcached_store, ActiveSupport::Cache::MemcachedStore.new(
      "127.0.0.1:11211",
      support_cas: true,
      auto_eject_hosts: false,  # avoids more cache consistency issues
      default_ttl: 6.hours.to_i, # in case of network errors when sending a delete
    )
```

throws this error: (using `servers: ["127.0.0.1:11211"]` doesn't work either)

```
.rvm/gems/ruby-2.5.7/gems/memcached-1.8.0/lib/memcached/memcached.rb:209:in `block in set_servers': Servers must be either in the format 'host:port[:weight]' (e.g., 'localhost:11211' or  'localhost:11211:10') for a network server, or a valid path to a Unix domain socket (e.g., /var/run/memcached). (ArgumentError)
``` 

This config works for me, note that using `servers:` named parameter also doesn't work:

```ruby
config.identity_cache_store = :memcached_store, 
      Memcached.new(
        memcached_hosts, # ["127.0.0.1:11211"]
        support_cas: true,
        auto_eject_hosts: false,  # avoids more cache consistency issues
        default_ttl: 6.hours.to_i, # in case of network errors when sending a delete
      )
```

Is this correct and Readme file outdated or am I missing something here?

I'm using identity_cache 1.0.1 with Rails 6.0.2.2.

**Comment by mani47** [comment]
Just found this PR: https://github.com/Shopify/identity_cache/pull/353

Any particular reason why it's not merged?

**Comment by mani47** [comment]
Thank you.
