### ISSUE TITLE
Rails Optimized Cache::Entry coder breaks IDC

### ISSUE THREAD

**Issue by jeromecornet** [Shopify/identity_cache#493]
Looks like this PR https://github.com/rails/rails/pull/42025 introduced a raw: parameter to the deserialize_entry of the memcache used by IDC (when configured to use mem_cache_store)

@byroot I don't really know whether the intention is to update IDC or keep backwards compatibility in rails, so I'm raising the issue against IDC (although it may be a problem with the original PR) but I figured that you would see it anyway.

=> #<ArgumentError: missing keyword: :raw>
Backtrace
```
"/app/vendor/bundle/ruby/2.7.0/bundler/gems/rails-08e3e663ca70/activesupport/lib/active_support/cache/mem_cache_store.rb:247:in `deserialize_entry'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/identity_cache-01e90ed9fffe/lib/identity_cache/mem_cache_store_cas.rb:14:in `block (4 levels) in cas'",
 "/app/vendor/bundle/ruby/2.7.0/gems/dalli-2.7.11/lib/dalli/client.rb:276:in `cas_core'",
 "/app/vendor/bundle/ruby/2.7.0/gems/dalli-2.7.11/lib/dalli/client.rb:116:in `cas'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/identity_cache-01e90ed9fffe/lib/identity_cache/mem_cache_store_cas.rb:13:in `block (3 levels) in cas'",
 "/app/vendor/bundle/ruby/2.7.0/gems/dalli-2.7.11/lib/dalli/client.rb:267:in `with'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/identity_cache-01e90ed9fffe/lib/identity_cache/mem_cache_store_cas.rb:12:in `block (2 levels) in cas'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/rails-08e3e663ca70/activesupport/lib/active_support/cache.rb:775:in `block in instrument'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/rails-08e3e663ca70/activesupport/lib/active_support/notifications.rb:207:in `block in instrument'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/rails-08e3e663ca70/activesupport/lib/active_support/notifications/instrumenter.rb:44:in `instrument'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/rails-08e3e663ca70/activesupport/lib/active_support/notifications.rb:207:in `instrument'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/rails-08e3e663ca70/activesupport/lib/active_support/cache.rb:775:in `instrument'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/identity_cache-01e90ed9fffe/lib/identity_cache/mem_cache_store_cas.rb:11:in `block in cas'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/rails-08e3e663ca70/activesupport/lib/active_support/cache/mem_cache_store.rb:256:in `rescue_error_with'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/identity_cache-01e90ed9fffe/lib/identity_cache/mem_cache_store_cas.rb:10:in `cas'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/identity_cache-01e90ed9fffe/lib/identity_cache/cache_fetcher.rb:179:in `upsert'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/identity_cache-01e90ed9fffe/lib/identity_cache/cache_fetcher.rb:86:in `fetch_without_fill_lock'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/identity_cache-01e90ed9fffe/lib/identity_cache/cache_fetcher.rb:78:in `fetch'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/identity_cache-01e90ed9fffe/lib/identity_cache/memoized_cache_proxy.rb:81:in `block (2 levels) in fetch'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/identity_cache-01e90ed9fffe/lib/identity_cache/memoized_cache_proxy.rb:154:in `fetch_memoized'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/identity_cache-01e90ed9fffe/lib/identity_cache/memoized_cache_proxy.rb:79:in `block in fetch'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/rails-08e3e663ca70/activesupport/lib/active_support/notifications.rb:207:in `block in instrument'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/rails-08e3e663ca70/activesupport/lib/active_support/notifications/instrumenter.rb:44:in `instrument'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/rails-08e3e663ca70/activesupport/lib/active_support/notifications.rb:207:in `instrument'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/identity_cache-01e90ed9fffe/lib/identity_cache/memoized_cache_proxy.rb:76:in `fetch'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/identity_cache-01e90ed9fffe/lib/identity_cache.rb:150:in `fetch'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/identity_cache-01e90ed9fffe/lib/identity_cache/cache_key_loader.rb:33:in `load'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/identity_cache-01e90ed9fffe/lib/identity_cache/cached/primary_index.rb:16:in `fetch'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/identity_cache-01e90ed9fffe/lib/identity_cache/with_primary_index.rb:126:in `fetch_by_id'",
 "/app/vendor/bundle/ruby/2.7.0/bundler/gems/identity_cache-01e90ed9fffe/lib/identity_cache/with_primary_index.rb:140:in `fetch'",
 ```

You should be able to repro with any app that uses rails master and IDC.

**Comment by byroot** [comment]
Thanks for the report, I'll take a look tomorrow. cc @casperisfine
